### ISSUE TITLE
add a command that links to the source code

### ISSUE THREAD

**Issue by MoralCode** [RITlug/ritlug-discord-bot#11]
Would a command such as `/source` (or a note at the end of a help message within a `/help` command) be potentially useful to add as a pull request?

hacktoberfest has me itching to do more pull requests for a free shirt

**Comment by kenshineto** [comment]
Just posting here as well. Feel free to add it as I said in the discord. Also I would make a new rs file and attach it to the commands module just to follow the current code convention. If you want to test it, you have to do `@bot_name register` to register the slash commands on the server. :)

**Comment by MoralCode** [comment]
is there a preference as to either method of adding this (new command vs help command)?

**Comment by kenshineto** [comment]
Just add it as a new command called `/source` like you suggested. There really isn't a `/help` command rn, so if you want to implement that, you can too!  A help command imo would just list the commands, what they do, and the arguments for them. Though suggest anything else if you think differently.

**Comment by kenshineto** [comment]
Turns out that Tristan already made a `/help` command. But if you want to make the `/source` command you still can.
